### ISSUE TITLE
기본 라이브러리 세팅

### ISSUE THREAD

**Issue by fkdl0048** [The-Day-In-1984/1984_Project#10]
프로젝트에 사용할 라이브러리 세팅

- [ ] TextMeshPro
- [x] Cinemachine
- [ ] Yarnspinner
- [x] Dotween

**Comment by fkdl0048** [comment]
추가적으로 필요한 라이브러리 알려주세요

@ccmuk58 사용하기로 했던 대사 패키지 알려주시면 미리 기록하고 설치하겠습니다

**Comment by ccmuk58** [comment]
@fkdl0048 헉 그거 아마 민경님이 찾아오신걸로 알고있어요 
@kyoonge

**Comment by ccmuk58** [comment]
https://docs.yarnspinner.dev/using-yarnspinner-with-unity/installation-and-setup

Package Manager가 권장 설치 방법이라고 합니다!
