### ISSUE TITLE
Feat: 대화 시스템 개발 / 대화 연출

### ISSUE THREAD

**Issue by ccmuk58** [The-Day-In-1984/1984_Project#137]
# Feat : 대화 시스템 개발 / 대화 연출

## Todo

- [x] 등장 및 사라짐 헤더 적용
- [x] 타이핑 효과

## ETC

현재 작업 현황
타이핑 효과 까지 "작동은 잘 됨"
꼭 리팩토링 하겠습니다 ,,,,,,,,,,,

**Comment by fkdl0048** [comment]
![image](https://github.com/The-Day-In-1984/1984_Project/assets/84510455/d6bbe520-ee30-409d-975b-5d9eb594f476)
