### ISSUE TITLE
Bug: TMP 한글 폰트 버그

### ISSUE THREAD

**Issue by fkdl0048** [The-Day-In-1984/1984_Project#138]
# Bug: 버그 내용

한글 약 10%정도 소실

## Reasons

Genrate단계에서 아마 실수..? 

## Solution

다른 고딕 폰트나, 인수 다시 설정해보기..

**Comment by kyoonge** [comment]
todo리스트 대박이다... 넌 진짜 정리정안

**Comment by fkdl0048** [comment]
어떤데!

**Comment by kyoonge** [comment]
너무 정리를 잘하잖아; 확신의 J인데
