### ISSUE TITLE
Bug: Aspose.cell 어셈블리 버전 에러

### ISSUE THREAD

**Issue by ccmuk58** [The-Day-In-1984/1984_Project#85]
# Bug : Aspose.cell 어셈블리 버전 에러
라이브러리 추가와 함께 어셈블리 버전 유효성 검사 관련 에러 발생

## Reasons
```
Assembly 'Assets/Packages/Aspose.Cells.23.3.0/lib/netstandard2.0/Aspose.Cells.dll' will not be loaded due to errors:
Aspose.Cells references strong named System.Security.Cryptography.Pkcs Assembly references: 4.0.3.2 Found in project: 4.0.4.0.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"
```
NuGet 및 Aspose.Cells 라이브러리를 임포트함과 동시에 위와 같은 에러로 사용을 할 수 없었음 , , 
(어셈블리 버전 관련 유효성 검사 문제)

## Solution
Assembly Version Validation 옵션을 꺼보니 정상 작동 하긴 하는데,
비권장 방법이긴 함 ( 다른 방법들 실패 ,,)

Assembly Version Validation 옵션을 끈 상태로 push 할 예정
(Edit - Project Settings - Player - Other Settings - Assembly Version Validation)

## ETC
혹시나 나중에 관련 이슈가 생길 수도,,?

@fkdl0048 @kyoonge 
확인 끝나면 Project Setting PR 후 이슈 닫을 예정
이상.

**Comment by kyoonge** [comment]
오...... 무섭다
확인 완.

**Comment by fkdl0048** [comment]
> (어셈블리 버전 관련 유효성 검사 문제)  

다른 라이브러리나 플러그인을 Import할 때 많이 발생하는 것 같은데 나도 그냥 무시하거나 넘기는 경우가 많았어..  

혹시 디버깅하면서 잘 알게되면 알려줘!
