### ISSUE TITLE
프로젝트 기본 설정

### ISSUE THREAD

**Issue by fkdl0048** [The-Day-In-1984/1984_Project#9]
- [x] #12
- [x] #11
- [x] #15
- [x] #16
- [x] #13
- [x] #17
- [x] #10
- [x] #40

**Comment by fkdl0048** [comment]
추가적으로 필요한 내용들 추가해주세요~!

**Comment by ccmuk58** [comment]
확인하고 있으면 추가하도록 하겠습니다 !!
