### ISSUE TITLE
GitIgnore rider 설정

### ISSUE THREAD

**Issue by fkdl0048** [The-Day-In-1984/1984_Project#99]
# Bug: 버그 내용

자꾸 `1984/.idea/.idea.1984/.idea/workspace.xml`잡히는 문제..  

## Reasons

ignore에 등록이 안된 것 같은데 그전에 문제 없는지 검증

## Solution

![image](https://user-images.githubusercontent.com/84510455/231073923-db3843c3-79a2-49d2-8c21-f782000773d3.png)

**Comment by ccmuk58** [comment]
저거 자꾸 잡히긴 하더라고

전에 프로젝트 할 때 찾아본 적 있어
그 때 기억으론 이미 올라가 있는 파일은 ignore 적용이 안된다고 했던 것 같아
그래서 한 번 지우고 push해야 된다고 했던 것 같은데 ,,

전에 할 때는 그냥 안고 갔던 문제라 확실하지는 않음!!

**Comment by fkdl0048** [comment]
이번에 내가 확실하게 알아보고 공유할께..!
